"""
task_3_4_verl_config.py — Generate VERL/GRPO config and SLURM submission script.

Queries the cluster for available GPU resources and generates an appropriately
scaled VERL hydra config + SLURM submission script.

Also cancels the old GRPO job 1855278 if still pending.

Output:
  configs/cps_anomaly_grpo.yaml
  slurm/submit_anomaly_grpo.sh
  outputs/phase3/verl_config_summary.json
"""

import json
import subprocess
from pathlib import Path

ROOT   = Path("/home/simran/allspark-data-exploration/CPS-Debugger")
P3_OUT = ROOT / "outputs/phase3"
P3_OUT.mkdir(parents=True, exist_ok=True)
(ROOT / "configs").mkdir(exist_ok=True)
(ROOT / "slurm").mkdir(exist_ok=True)


def query_cluster():
    """Query available partitions and GPU types."""
    try:
        result = subprocess.run(
            ["sinfo", "-p", "gpu,long,short", "--format=%P %G %m %a %D", "--noheader"],
            capture_output=True, text=True, timeout=10
        )
        lines = result.stdout.strip().split("\n")
        partitions = []
        for line in lines:
            parts = line.split()
            if len(parts) >= 5:
                partitions.append({
                    "partition": parts[0].rstrip("*"),
                    "gres":      parts[1],
                    "mem_mb":    parts[2],
                    "available": parts[3],
                    "n_nodes":   parts[4],
                })
        return partitions
    except Exception as e:
        print(f"  sinfo query failed: {e}")
        return []


def select_config(partitions):
    """Determine best GPU config based on cluster availability."""
    # Check for A100 80GB, A100 40GB, A6000, V100
    gpu_config = {
        "partition":   "long",
        "n_gpus":      4,
        "gpu_type":    "A100",
        "model":       "Qwen/Qwen2.5-Coder-7B-Instruct",
        "use_lora":    False,
        "lora_rank":   0,
        "group_size":  8,
        "batch_size":  32,
        "grad_accum":  2,
        "mem_gb":      128,
        "time":        "2-00:00:00",
    }

    for p in partitions:
        gres = p.get("gres", "").lower()
        if "a100" in gres or "gpu" in gres:
            gpu_config["partition"] = p["partition"]
            # Try to detect GPU memory from gres string
            if "80" in gres:
                gpu_config["use_lora"] = False  # full fine-tuning
            elif "40" in gres:
                gpu_config["use_lora"] = True
                gpu_config["lora_rank"] = 16
            break

    return gpu_config


def make_yaml_config(cfg: dict) -> str:
    lora_section = ""
    if cfg["use_lora"]:
        lora_section = f"""
  lora:
    enable: true
    rank: {cfg["lora_rank"]}
    alpha: {cfg["lora_rank"] * 2}
    target_modules: ["q_proj", "k_proj", "v_proj", "o_proj"]
"""

    return f"""# CPS Anomaly Explanation GRPO Configuration
# Generated by task_3_4_verl_config.py
# Model: {cfg["model"]}
# GPUs: {cfg["n_gpus"]}x {cfg["gpu_type"]}  LoRA: {cfg["use_lora"]}

data:
  train_files: {ROOT}/outputs/phase3/grpo_train.jsonl
  val_files:   {ROOT}/outputs/phase3/anomaly_eval_dataset.jsonl
  prompt_key:  prompt
  response_key: response
  max_prompt_length: 2048
  max_response_length: 512

actor_rollout_ref:
  model:
    path: {cfg["model"]}
    enable_gradient_checkpointing: true{lora_section}
  actor:
    optim:
      lr: 1.0e-6
      lr_scheduler: cosine
      warmup_steps: 50
    ppo_mini_batch_size: {cfg["batch_size"]}
    ppo_micro_batch_size: {max(1, cfg["batch_size"] // cfg["n_gpus"])}
    grad_clip: 1.0
  rollout:
    temperature: 1.0
    top_p: 0.95
    log_prob_micro_batch_size: {max(1, cfg["batch_size"] // cfg["n_gpus"])}
    tensor_model_parallel_size: {cfg["n_gpus"]}
  ref:
    log_prob_micro_batch_size: {max(1, cfg["batch_size"] // cfg["n_gpus"])}

critic:
  model:
    path: {cfg["model"]}
  optim:
    lr: 1.0e-5
  ppo_micro_batch_size: {max(1, cfg["batch_size"] // cfg["n_gpus"])}

reward_model:
  reward_fn_path: {ROOT}/scripts/phase3_reward_anomaly.py
  reward_fn:      compute_score

algorithm:
  gamma: 1.0
  lam: 1.0
  adv_estimator: grpo
  kl_ctrl:
    type: fixed
    kl_coef: 0.001
  grpo_group_size: {cfg["group_size"]}

trainer:
  project_name:       cps_debugger
  experiment_name:    anomaly_grpo_v1
  n_gpus_per_node:    {cfg["n_gpus"]}
  nnodes:             1
  total_epochs:       3
  save_freq:          1
  val_freq:           1
  default_local_dir:  {ROOT}/outputs/phase3/checkpoints/anomaly_grpo_v1
  logger:             ["console", "wandb"]
"""


def make_slurm_script(cfg: dict) -> str:
    python = "/home/simran/.conda/envs/slimllm/bin/python3"
    return f"""#!/bin/bash
#SBATCH --job-name=cps_anomaly_grpo
#SBATCH --partition={cfg["partition"]}
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --gres=gpu:{cfg["n_gpus"]}
#SBATCH --mem={cfg["mem_gb"]}G
#SBATCH --time={cfg["time"]}
#SBATCH --output={ROOT}/outputs/slurm/%x_%j.out
#SBATCH --error={ROOT}/outputs/slurm/%x_%j.err

set -euo pipefail

REPO={ROOT}
PYTHON={python}
OUT="$REPO/outputs/phase3"

echo "Host: $(hostname)"
echo "Start: $(date)"
echo "GPUs: $SLURM_GPUS_ON_NODE"
nvidia-smi --list-gpus 2>/dev/null | head -5 || true

module load cuda12.6/toolkit/12.6.2 2>/dev/null || true
export PATH="/home/simran/.conda/envs/slimllm/bin:$PATH"

if [[ -z "${{CUDA_VISIBLE_DEVICES:-}}" ]]; then
  export CUDA_VISIBLE_DEVICES=$(seq -s, 0 $(({cfg["n_gpus"]}-1)))
fi

cd "$REPO"

# ── Step 0: Verify prerequisites ──────────────────────────────────────────────
echo "[Step 0] Checking prerequisites..."
for f in \\
  "$OUT/anomaly_eval_dataset.jsonl" \\
  "$OUT/grpo_train.jsonl" \\
  "$OUT/sft_anomaly_train.jsonl" \\
  "$REPO/scripts/phase3_reward_anomaly.py"; do
  if [[ ! -f "$f" ]]; then
    echo "  ERROR: Missing $f"
    exit 1
  fi
done
echo "  All prerequisites found."

# ── Step 1: Install VERL if needed ────────────────────────────────────────────
echo ""
echo "[Step 1] Checking VERL..."
if ! $PYTHON -c "import verl" 2>/dev/null; then
  echo "  Installing verl..."
  $PYTHON -m pip install verl --quiet
fi
echo "  VERL ready."

# ── Step 2: SFT warmup ────────────────────────────────────────────────────────
echo ""
echo "[Step 2] SFT warmup (1 epoch on $(wc -l < $OUT/sft_anomaly_train.jsonl) examples)..."
SFT_CKPT="$OUT/checkpoints/sft_anomaly_warmup"
mkdir -p "$SFT_CKPT"

torchrun --nproc_per_node={cfg["n_gpus"]} \\
  -m verl.trainer.fsdp_sft_trainer \\
  data.train_files="$OUT/sft_anomaly_train.jsonl" \\
  data.val_files="$OUT/sft_anomaly_val.jsonl" \\
  data.prompt_key=prompt \\
  data.response_key=response \\
  data.max_length=4096 \\
  model.partial_pretrain={cfg["model"]} \\
  trainer.project_name=cps_debugger \\
  trainer.experiment_name=sft_anomaly_warmup_v1 \\
  trainer.total_epochs=1 \\
  trainer.save_freq=999999 \\
  trainer.logger='["console"]' \\
  trainer.default_local_dir="$SFT_CKPT" \\
  2>&1 | tee "$OUT/sft_anomaly_warmup.log"

SFT_LATEST=$(ls -td "$SFT_CKPT"/global_step_* 2>/dev/null | head -1 || echo "{cfg["model"]}")
echo "  SFT warmup complete. Checkpoint: $SFT_LATEST"

# ── Step 3: GRPO training ──────────────────────────────────────────────────────
echo ""
echo "[Step 3] GRPO training (3 epochs)..."
GRPO_CKPT="$OUT/checkpoints/anomaly_grpo_v1"
mkdir -p "$GRPO_CKPT"

$PYTHON -m verl.trainer.main_ppo \\
  --config-name cps_anomaly_grpo \\
  --config-path "$REPO/configs" \\
  actor_rollout_ref.model.path="$SFT_LATEST" \\
  trainer.n_gpus_per_node={cfg["n_gpus"]} \\
  trainer.default_local_dir="$GRPO_CKPT" \\
  trainer.logger='["console"]' \\
  2>&1 | tee "$OUT/anomaly_grpo_training.log"

echo "  GRPO training complete."

# ── Step 4: Evaluate ──────────────────────────────────────────────────────────
echo ""
echo "[Step 4] Evaluating GRPO model..."
GRPO_LATEST=$(ls -td "$GRPO_CKPT"/global_step_* 2>/dev/null | head -1)

if [[ -n "$GRPO_LATEST" ]]; then
  ANTHROPIC_API_KEY="${{ANTHROPIC_API_KEY:-}}" \\
  $PYTHON -u scripts/task_3_1b_llm_zero_shot.py \\
    --model "$GRPO_LATEST" \\
    --n 250 \\
    2>&1 | tee "$OUT/anomaly_grpo_eval.log"
else
  echo "  No GRPO checkpoint found, skipping eval."
fi

echo ""
echo "Done: $(date)"
echo "All outputs in: $OUT"
"""


def main():
    # Cancel old GRPO job if still running
    print("Checking for old GRPO job 1855278...")
    try:
        result = subprocess.run(
            ["squeue", "-j", "1855278", "--noheader"],
            capture_output=True, text=True, timeout=10
        )
        if result.stdout.strip():
            print(f"  Job 1855278 still in queue: {result.stdout.strip()}")
            confirm = input("  Cancel it? [y/N] ").strip().lower()
            if confirm == "y":
                subprocess.run(["scancel", "1855278"], check=True)
                print("  Cancelled job 1855278.")
        else:
            print("  Job 1855278 not in queue (already done or expired).")
    except Exception as e:
        print(f"  Could not check/cancel job: {e}")

    # Query cluster
    print("\nQuerying cluster...")
    partitions = query_cluster()
    for p in partitions:
        print(f"  {p}")

    # Select config
    cfg = select_config(partitions)
    print(f"\nSelected config:")
    print(f"  partition={cfg['partition']}, gpus={cfg['n_gpus']}×{cfg['gpu_type']}")
    print(f"  model={cfg['model']}, lora={cfg['use_lora']}, group_size={cfg['group_size']}")

    # Write YAML
    yaml_path = ROOT / "configs/cps_anomaly_grpo.yaml"
    yaml_path.write_text(make_yaml_config(cfg))
    print(f"\nWrote {yaml_path}")

    # Write SLURM script
    slurm_path = ROOT / "slurm/submit_anomaly_grpo.sh"
    slurm_path.write_text(make_slurm_script(cfg))
    slurm_path.chmod(0o755)
    print(f"Wrote {slurm_path}")

    # Save summary
    (ROOT / "outputs/slurm").mkdir(exist_ok=True)
    summary = {
        "gpu_config":     cfg,
        "yaml_path":      str(yaml_path),
        "slurm_path":     str(slurm_path),
        "submit_command": f"sbatch {slurm_path}",
        "partitions_found": partitions,
    }
    (P3_OUT / "verl_config_summary.json").write_text(json.dumps(summary, indent=2))
    print("\nSaved verl_config_summary.json")
    print(f"\nTo submit: sbatch {slurm_path}")
    print("Done.")


if __name__ == "__main__":
    main()
